# Generated by Django 5.0.2 on 2024-03-21 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_svyaz_datetime_alter_svyaz_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='svyaz',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Сообщения от пользователей'},
        ),
    ]
