# Generated by Django 5.0.2 on 2024-03-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_options_alter_svyaz_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': '2. Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': '1. Товары'},
        ),
        migrations.AlterModelOptions(
            name='svyaz',
            options={'verbose_name': 'Запись', 'verbose_name_plural': '3. Сообщения от пользователей'},
        ),
    ]
