# Generated by Django 5.0.2 on 2024-03-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=500, verbose_name='Номер заказчика')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('message', models.CharField(blank=True, max_length=500, null=True, verbose_name='Сообщение')),
                ('price', models.CharField(max_length=100, verbose_name='Стоимость заказа')),
                ('unicnum', models.CharField(max_length=100, verbose_name='Номер заказа')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('status', models.CharField(choices=[('N', 'В ожидании'), ('W', 'Принят'), ('C', 'Завершен')], max_length=1, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Клиента',
                'verbose_name_plural': '1. Клиенты',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=150, verbose_name='Имя товара')),
                ('price_1_product', models.CharField(max_length=100, verbose_name='Цена за 1 товар')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('price_all', models.CharField(max_length=100, verbose_name='Общая цена')),
                ('id_order', models.CharField(max_length=100, verbose_name='Номер заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': '2. Заказы',
            },
        ),
    ]
